### ISSUE TITLE
Make it work with higher order components

### ISSUE THREAD

**Issue by ancashoria** [zestia/ember-auto-focus#2]
Hey,
great job with this plugin.
Is it possible to make it work with higher order components ? 
ex: 
`{{custom-validated-input ...}}`

**Comment by amk221** [comment]
After some discussion on slack, we decided the easiest option (for now) is to allow a selector to be passed in ([change](https://github.com/amk221/ember-auto-focus/commit/5f469d13d4d46876e587be3abe9b55f5afc27068#diff-9119b45f58daa678a8462a8515714da1R51)).
