### ISSUE TITLE
New release with ember-modifier v4

### ISSUE THREAD

**Issue by andreyfel** [zestia/ember-auto-focus#24]
@amk221 Could you please cut a new release with ember-modifier v4 dependency?

**Comment by amk221** [comment]
Thanks for the nudge

**Comment by sergiofenoll** [comment]
Hi, you released this as version 4.5.0. Any chance you could undo this and release it as a major version bump? ember-modifier v4 is breaking AFAIK and our app still uses an older version of ember-modifer which causes it to break when v4.5.0 of ember-auto-focus is pulled in.

**Comment by amk221** [comment]
Sure, apologies

**Comment by amk221** [comment]
ok I think that should be fixed now

v5 for @andreyfel 
v4.5.1 for @sergiofenoll

**Comment by andreyfel** [comment]
Thank you @amk221!
