### ISSUE TITLE
Add tabindex automatically

### ISSUE THREAD

**Issue by BrennanRoberts** [zestia/ember-auto-focus#3]
Would it make sense for `ember-auto-focus` to automatically add a `tabindex` of -1 to its `selector` element (perhaps, only if it doesn't already have one or is a [tabbable element](https://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute))? .

**Comment by amk221** [comment]
I'd be reluctant to reach out of the component and start altering other components, it feels wrong.
What's your use-case? :)

**Comment by BrennanRoberts** [comment]
Hey @amk221: we're usually going to be wrapping headers so it seems like it could be assumed that we want it to have `tabindex="-1"`, and omitting it accidentally would cause the autofocus to fail. I understand the desire to not mutate other components, though.

**Comment by amk221** [comment]
I asked around on Slack and it confirmed my thoughts, think it's a no-go. Cheers for the input though!
