### ISSUE TITLE
Make the component not dependent on jQuery

### ISSUE THREAD

**Issue by acorncom** [zestia/ember-auto-focus#4]
As the community slowly shifts away from jQuery, it'd be useful to not use jQuery here too. Would probably take a major version bump though due to selectors potentially needing to change?

**Comment by amk221** [comment]
Thanks, input on this appreciated:
https://github.com/amk221/ember-auto-focus/compare/nojquery

**Comment by acorncom** [comment]
That looks reasonable.  I've been watching Miguel Camba as he sends in various PRs to remove jQuery and it looks like he also switches the test system away from jQuery completely, as it ensures that it doesn't accidentally get re-introduced 😀 

Here's an example PR showing the steps it takes: https://github.com/DockYard/ember-changeset/pull/185

**Comment by amk221** [comment]
yeh, I'm going to wait for an official migration path before starting anything like that. I've got too many other addons and work to do :)

**Comment by acorncom** [comment]
👍 I hear you 😀

**Comment by amk221** [comment]
😌 ok I got that merged as 2.0.1 (messed up the release)
