### ISSUE TITLE
Slow Build

### ISSUE THREAD

**Issue by btecu** [zestia/ember-auto-focus#6]
Considering how _simple_ the component is, it surely takes a very long time:
![image](https://user-images.githubusercontent.com/7517745/56504891-09232800-64e8-11e9-94c4-35d616d5a173.png)

My guess would be to look into the included polyfills.

**Comment by amk221** [comment]
Thanks, there's certainly nothing special going on... I'll investigate.

**Comment by amk221** [comment]
@btecu Was that with a fresh ember-cli app? What version?

**Comment by btecu** [comment]
It's an existing application, using `ember-cli` `3.8` on a Windows machine.

**Comment by amk221** [comment]
Ok thank you. Would you be able to do me a favour?

`ember new example`
`ember install @zestia/ember-auto-focus`
`ember server`

...just to see if you get the same slowness as your existing app? 

In the meantime, I'll set up a windows vm

**Comment by amk221** [comment]
Hi @btecu, are you still experiencing this? Closing if not.

**Comment by btecu** [comment]
I haven't had to retry, so I'll close for now.
